### ISSUE TITLE
Can I detect outliers even itemtype is 'nominal'?

### ISSUE THREAD

**Issue by seonghobae** [philchalmers/faoutlier#3]
Hi, Phil
I saw the paper at 'Applied psychological measurement'. After that, I produce a silly question. Can I detect outliers for influential cases even item-type is nominal? I guess I can't do this, but I may find outliers even item-type is nominal.

Seongho

**Comment by philchalmers** [comment]
Sure, but the problem is that categorical models often have next to no influence on fit because each item in isolation has little information. What would a univariate outlier look like on a categorical item: 5? 7? How much influence does this have on the model as a whole? So yes you can find them, but the odds are extremely low.

**Comment by seonghobae** [comment]
My main consideration is relative with the 'Devide and Conquer' approach for the treat inaccuracy  in Marginal Maximum Likelihood Estimation with EM/QMCEM; For the nominal response and non-sequential latent class model in `mirt::mdirt()` with unequal categories per item with type 'nominal responses'.

**Comment by philchalmers** [comment]
I'd have to think about it, but this package is mostly about locating influential response patterns. So it's likely not what you want for comparing estimators.
